#! /bin/bash

kubectl "$@"

if [ "$1" == "config" ] && [ "$2" == "use-context" ]; then
  # Detect OS type
  if [[ "$OSTYPE" =~ ^(darwin) ]]; then
    os="darwin"
  elif [[ "$OSTYPE" = "linux-gnu" ]]; then
    os="linux"
  else
    echo "os type unsupported"
    exit 1
  fi

  # Get client & server kube version
  export client=($(kubectl version --output=yaml | grep -Eo "gitVersion: \v([0-9.]+)" | sed -E 's/gitVersion: v([0-9.]+)/\1/'))

  # Compare version and search for the binary
  if [ -n "${client[1]}" ]; then
    server=($(echo ${client[1]} | tr "-" "\n"))
    if [ "$client" != "$server" ]; then
      export found=$(ls ~/.kube/ | grep kubectl-"$server")
      if [ -z "$found" ]; then
        echo "Downloading kubectl-$server"
        curl -L https://storage.googleapis.com/kubernetes-release/release/v"$server"/bin/"$os"/amd64/kubectl -o ~/.kube/kubectl-"$server"
      fi
      sudo cp ~/.kube/kubectl-"$server" /usr/local/bin/kubectl
    fi
  fi
fi
