#! /bin/bash

kubectl "$@"

if [ "$1" == "config" ] && [ "$2" == "use-context" ]; then
  export client=($(kubectl version | grep -Eo "GitVersion:\"v([0-9.]+)\"" | sed -E 's/GitVersion:"v([0-9.]+)"/\1/'))

  if [ -n "${client[1]}" ]; then
    server=($(echo ${client[1]} | tr "-" "\n"))
    if [ "$client" != "$server" ]; then
      export found=$(ls ~/.kube/ | grep kubectl-"$server")
      if [ -z "$found" ]; then
        echo "Downloading kubectl-$server"
        curl -L https://storage.googleapis.com/kubernetes-release/release/v"$server"/bin/linux/amd64/kubectl -o ~/.kube/kubectl-"$server"
      fi
      cp ~/.kube/kubectl-"$server" /usr/local/bin/kubectl
    fi
  fi
fi
